### PR TITLE
Fix/Resolved Image Error

### LINKED ISSUE #3: Resolve image error in name screen
Without selecting image a user are not being able to go in home sceen , try to resolve this error in flutter

### PR DESCRIPTION
**Pull request by ayato91**
Now it will show a snackbar whenever there is no image selected.
Fix #3

### CODE REVIEW

**Comment by simplybest12** [comment]
what if user doesnt want to choose an image? @ayato91

**Comment by ayato91** [comment]
Then we can add a sample picture as default one and also get the confirmation by asking yes or no in the snackbar

**Comment by ayato91** [comment]
@simplybest12 Can you check and provide review now?

**Comment by simplybest12** [comment]
assigning it to you @ayato91

**Comment by simplybest12** [comment]
looks fine...now merging this pull request to the branch
@ayato91

**Pull request merged**
